/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package egui;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;


/**
 *
 * @author Marvin
 */
public class addscore extends javax.swing.JFrame {

    String values[][];
    JLabel names[];
    JTextField inputs[];
    int counter = 0;
    int grade_id = 8;
    int x = 0;
    String id ="";
    String highscore="";
    int arr[];


    /**
     * Creates new form addscore
     */
    public addscore(String id,String highscore,String quarter,String worktype) {
        this.id = id;
        this.highscore = highscore;
        initComponents();
        int x = 0;
        System.out.println("ID:"+id);
        System.out.println("highscore:"+highscore);
        lblhs.setText("Number of items: "+highscore);
        this.setLocationRelativeTo(null);
        try {
            
            DBKonek Konek = new DBKonek();
            Connection conn;
            conn = Konek.DBKonek();

            Statement stmt = conn.createStatement();
         

            stmt.execute("SELECT * FROM tbl_students");
            ResultSet rs = stmt.getResultSet();

            while (rs.next()) {
                x++;
            }

        } catch (SQLException e) {
            e.printStackTrace();

        }

        names = new JLabel[x];
//         final JTextField 
        inputs = new JTextField[x];
        values = new String[x][2];
        try {
            DBKonek Konek = new DBKonek();
            Connection conn;
            conn = Konek.DBKonek();

            Statement stmt = conn.createStatement();

            x = 0;
            stmt.execute("SELECT * FROM tbl_students");
            ResultSet rs = stmt.getResultSet();
            while (rs.next()) {

                values[x][0] = rs.getString("s_ID");
                values[x][1] = "" + rs.getString("s_fname") + " " + rs.getString("s_mname") + " " + rs.getString("s_lname") + "";
                x++;
            }
            System.out.println(x);

            int height = 25;
            for (int i = 0; i < x; i++) {
                names[i] = new JLabel(values[i][1]);
                inputs[i] = new JTextField();
                view.add(names[i]);
                view.add(inputs[i]);
                names[i].setBounds(20, height, 100, 25);
                inputs[i].setBounds(150, height, 100, 25);
                inputs[i].setText("0");
//               names[i].setLocation(0,height);
//               inputs[i].setLocation(130,height);
//               inputs[i].setPreferredSize(new Dimension(20,15));
//                inputs[i].setMaximumSize(new Dimension(75,50));
                height += 50;

            }
            arr= new int [names.length];
//           JScrollPane js = new JScrollPane(view,JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
//           js.setBounds(40,40,400,400);
//           this.add(js);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        js = new javax.swing.JScrollPane();
        view = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        lblhs = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout viewLayout = new javax.swing.GroupLayout(view);
        view.setLayout(viewLayout);
        viewLayout.setHorizontalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );
        viewLayout.setVerticalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        js.setViewportView(view);

        save.setBackground(new java.awt.Color(0, 0, 102));
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        lblhs.setText("Number Of Items:");

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD SCORES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(137, 137, 137))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(js, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblhs, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lblhs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(js, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        js.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        js.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
            int z =0;
            int counter = 0;
            DBKonek Konek = new DBKonek();
            Connection conn;
            conn = Konek.DBKonek();
            Statement stmt = conn.createStatement();
            Statement stmt2 = conn.createStatement();
            
                    for(int i = 0; i < names.length;i++) {
                        int score = Integer.parseInt(inputs[i].getText());
                        if (score < Integer.parseInt(highscore)){
                             arr[i] = score;
                             counter ++;
                        }
                        else{
 
                               JOptionPane.showMessageDialog(null,"Score exceeds!");
                               counter = 0;
                               break;

                        }

                    }
                        if (counter == names.length){

                            for(int i = 0; i < names.length;i++) {

                                int score = arr[i];
                                System.out.println(values[i][0] + " " + id + " " + score +i);         
                                System.out.print(score);
                                    stmt.executeUpdate("INSERT INTO tbl_rawscore " + " VALUES(null,'"+ id +"','" + values[i][0]+ "',"+ score +")");
                                    inputs[i].setEnabled(false);
                                                        



                            }
                                JOptionPane.showMessageDialog(null, "SUBMITTED!");
                                this.setVisible(false);
                        }

      
            
            
            //ResultSet rs = stmt.getResultSet();
        } catch (SQLException e) {
        }        // TODO add your handling code here:

    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public void addrecord() {
//        JButton savebutt = new JButton("Save");
//        this.add(savebutt);
//        savebutt.setBounds(50,500,100,50);
////        this.setSize(500,700);
//////        JPanel view = new JPanel();
//        view.setLayout(new BoxLayout(view, BoxLayout.Y_AXIS));
//        view.setBounds(20,10,400,400);

        //JLabel name[] = new JLabel[rs.length];
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addscore("","","","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane js;
    private javax.swing.JLabel lblhs;
    private javax.swing.JButton save;
    private javax.swing.JPanel view;
    // End of variables declaration//GEN-END:variables
}
